const PORTFOLIO_ACTION_TYPES = {
  START_PORTFOLIO_FETCH: "START_PORTFOLIO_FETCH",
  PORTFOLIO_FETCH_FAIL: "PORTFOLIO_FETCH_FAIL",
  PORTFOLIO_FETCH_SUCCESS: "PORTFOLIO_FETCH_SUCCESS",
  START_ADDING_NEW_TRANSACTION: "START_ADDING_NEW_TRANSACTION",
  ADDING_NEW_TRANSACTION_FAIL: "ADDING_NEW_TRANSACTION_FAIL",
  ADDING_NEW_TRANSACTION_SUCCESS: "ADDING_NEW_TRANSACTION_SUCCESS",
  START_DELETING_TRANSACTION_BY_ID: "START_DELETING_TRANSACTION_BY_ID",
  DELETE_TRANSACTION_BY_ID_FAIL: "DELETE_TRANSACTION_BY_ID_FAIL",
  DELETE_TRANSACTION_BY_ID_SUCCESS: "DELETE_TRANSACTION_BY_ID_SUCCESS",
  START_UPDATING_TRANSACTION_BY_ID: "START_UPDATING_TRANSACTION_BY_ID",
  UPDATE_TRANSACTION_BY_ID_FAIL: "UPDATE_TRANSACTION_BY_ID_FAIL",
  UPDATE_TRANSACTION_BY_ID_SUCCESS: "UPDATE_TRANSACTION_BY_ID_SUCCESS",
  START_TRANSACTIONS_FOR_ASSET_FETCH: "START_TRANSACTIONS_FOR_ASSET_FETCH",
  FETCH_TRANSACTIONS_FOR_ASSET_FAIL: "FETCH_TRANSACTIONS_FOR_ASSET_FAIL",
  FETCH_TRANSACTIONS_FOR_ASSET_SUCCESS: "FETCH_TRANSACTIONS_FOR_ASSET_SUCCESS",
  START_REMOVING_ALL_TRANSACTIONS_FOR_ASSET:
    "START_REMOVING_ALL_TRANSACTIONS_FOR_ASSET",
  REMOVE_ALL_TRANSACTIONS_FOR_ASSET_FAIL:
    "REMOVE_ALL_TRANSACTIONS_FOR_ASSET_FAIL",
  REMOVE_ALL_TRANSACTIONS_FOR_ASSET_SUCCESS:
    "REMOVE_ALL_TRANSACTIONS_FOR_ASSET_SUCCESS"
};

export default PORTFOLIO_ACTION_TYPES;
