const CURRENCY_ACTION_TYPES = {
  FETCH_CURRENCIES: "FETCH_CURRENCIES",
  FETCH_CURRENCIES_SUCCESS: "FETCH_CURRENCIES_SUCCESS",
  FETCH_CURRENCIES_FAIL: "FETCH_CURRENCIES_FAIL",
  FETCH_MORE_CURRENCIES: "FETCH_MORE_CURRENCIES",
  FETCH_MORE_CURRENCIES_SUCCESS: "FETCH_MORE_CURRENCIES_SUCCESS",
  FETCH_MORE_CURRENCIES_FAIL: "FETCH_MORE_CURRENCIES_FAIL",
  NO_MORE_CURRENCIES: "NO_MORE_CURRENCIES",
  FETCH_CURRENCY_SUCCESS: "FETCH_CURRENCY_SUCCESS"
};

export default CURRENCY_ACTION_TYPES;
