const ASSET_DETAIL_ACTION_TYPES = {
  FETCH_ASSET_OVERVIEW: "FETCH_ASSET_OVERVIEW",
  ASSET_OVERVIEW_FAIL: "ASSET_OVERVIEW_FAIL",
  ASSET_OVERVIEW_SUCCESS: "ASSET_OVERVIEW_SUCCESS",
  FETCH_ASSET_MARKETS: "FETCH_ASSET_MARKETS",
  ASSET_MARKETS_FAIL: "ASSET_MARKETS_FAIL",
  ASSET_MARKETS_SUCCESS: "ASSET_MARKETS_SUCCESS",
  FETCH_ASSET_ABOUT: "FETCH_ASSET_ABOUT",
  ASSET_ABOUT_FAIL: "ASSET_ABOUT_FAIL",
  ASSET_ABOUT_SUCCESS: "ASSET_ABOUT_SUCCESS",
  INITIAL_ASSET_NEWS_FETCH: "INITIAL_ASSET_NEWS_FETCH",
  INITIAL_ASSET_NEWS_SUCCESS: "INITIAL_ASSET_NEWS_SUCCESS",
  INITIAL_ASSET_NEWS_FAIL: "INITIAL_ASSET_NEWS_FAIL",
  FETCH_MORE_ASSET_NEWS: "FETCH_MORE_ASSET_NEWS",
  MORE_ASSET_NEWS_SUCCESS: "MORE_ASSET_NEWS_SUCCESS",
  MORE_ASSET_NEWS_FAIL: "MORE_ASSET_NEWS_FAIL",
  INITIAL_ASSET_EVENTS_FETCH: "INITIAL_ASSET_EVENTS_FETCH",
  INITIAL_ASSET_EVENTS_SUCCESS: "INITIAL_ASSET_EVENTS_SUCCESS",
  INITIAL_ASSET_EVENTS_FAIL: "INITIAL_ASSET_EVENTS_FAIL",
  FETCH_MORE_ASSET_EVENTS: "FETCH_MORE_ASSET_EVENTS",
  MORE_ASSET_EVENTS_SUCCESS: "MORE_ASSET_EVENTS_SUCCESS",
  MORE_ASSET_EVENTS_FAIL: "MORE_ASSET_EVENTS_FAIL",
  UPDATE_ASSET_EVENT_FILTERS: "UPDATE_ASSET_EVENT_FILTERS",
  NO_MORE_ASSET_NEWS: "NO_MORE_ASSET_NEWS",
  NO_MORE_ASSET_EVENTS: "NO_MORE_ASSET_EVENTS"
};

export default ASSET_DETAIL_ACTION_TYPES;
