const ASSET_DETAIL_ACTION_TYPES = {
  FETCH_ASSET_OVERVIEW: "FETCH_ASSET_OVERVIEW",
  FETCH_ASSET_OVERVIEW_FAIL: "FETCH_ASSET_OVERVIEW_FAIL",
  FETCH_ASSET_OVERVIEW_SUCCESS: "FETCH_ASSET_OVERVIEW_SUCCESS",
  FETCH_ASSET_MARKETS: "FETCH_ASSET_MARKETS",
  FETCH_ASSET_MARKETS_FAIL: "FETCH_ASSET_MARKETS_FAIL",
  FETCH_ASSET_MARKETS_SUCCESS: "FETCH_ASSET_MARKETS_SUCCESS",
  FETCH_ASSET_ABOUT: "FETCH_ASSET_ABOUT",
  FETCH_ASSET_ABOUT_FAIL: "FETCH_ASSET_ABOUT_FAIL",
  FETCH_ASSET_ABOUT_SUCCESS: "FETCH_ASSET_ABOUT_SUCCESS",
  FETCH_ASSET_NEWS: "FETCH_ASSET_NEWS",
  FETCH_ASSET_NEWS_SUCCESS: "FETCH_ASSET_NEWS_SUCCESS",
  FETCH_ASSET_NEWS_FAIL: "FETCH_ASSET_NEWS_FAIL",
  FETCH_MORE_ASSET_NEWS: "FETCH_MORE_ASSET_NEWS",
  FETCH_MORE_ASSET_NEWS_SUCCESS: "FETCH_MORE_ASSET_NEWS_SUCCESS",
  FETCH_MORE_ASSET_NEWS_FAIL: "FETCH_MORE_ASSET_NEWS_FAIL",
  FETCH_ASSET_EVENTS: "FETCH_ASSET_EVENTS",
  FETCH_ASSET_EVENTS_SUCCESS: "FETCH_ASSET_EVENTS_SUCCESS",
  FETCH_ASSET_EVENTS_FAIL: "FETCH_ASSET_EVENTS_FAIL",
  FETCH_MORE_ASSET_EVENTS: "FETCH_MORE_ASSET_EVENTS",
  FETCH_MORE_ASSET_EVENTS_SUCCESS: "FETCH_MORE_ASSET_EVENTS_SUCCESS",
  FETCH_MORE_ASSET_EVENTS_FAIL: "FETCH_MORE_ASSET_EVENTS_FAIL",
  UPDATE_ASSET_EVENT_FILTERS: "UPDATE_ASSET_EVENT_FILTERS",
  NO_MORE_ASSET_NEWS: "NO_MORE_ASSET_NEWS",
  NO_MORE_ASSET_EVENTS: "NO_MORE_ASSET_EVENTS",
  UPDATE_ASSET_OVERVIEW: "UPDATE_ASSET_OVERVIEW"
};

export default ASSET_DETAIL_ACTION_TYPES;
