const SUMMARY_ACTION_TYPES = {
  FETCH_TOP_COINS: "FETCH_TOP_COINS",
  FETCH_TOP_COINS_SUCCESS: "FETCH_TOP_COINS_SUCCESS",
  FETCH_TOP_COINS_FAIL: "FETCH_TOP_COINS_FAIL",
  FETCH_GAINERS_LOSERS: "FETCH_GAINERS_LOSERS",
  FETCH_GAINERS_LOSERS_SUCCESS: "FETCH_GAINERS_LOSERS_SUCCESS",
  FETCH_GAINERS_LOSERS_FAIL: "FETCH_GAINERS_LOSERS_FAIL",
  FETCH_NEWS_SUMMARY: "FETCH_NEWS_SUMMARY",
  FETCH_NEWS_SUMMARY_SUCCESS: "FETCH_NEWS_SUMMARY_SUCCESS",
  FETCH_NEWS_SUMMARY_FAIL: "FETCH_NEWS_SUMMARY_FAIL",
  FETCH_GLOBAL_SUMMARY: "FETCH_GLOBAL_SUMMARY",
  FETCH_GLOBAL_SUMMARY_SUCCESS: "FETCH_GLOBAL_SUMMARY_SUCCESS",
  FETCH_GLOBAL_SUMMARY_FAIL: "FETCH_GLOBAL_SUMMARY_FAIL",
  UPDATE_TOP_COINS: "UPDATE_TOP_COINS",
  UPDATE_GAINERS_LOSERS: "UPDATE_GAINERS_LOSERS"
};

export default SUMMARY_ACTION_TYPES;
