const SUMMARY_ACTION_TYPES = {
  START_TOP_COINS_FETCH: "START_TOP_COINS_FETCH",
  TOP_COINS_FETCH_SUCCESS: "TOP_COINS_FETCH_SUCCESS",
  TOP_COINS_FETCH_FAIL: "TOP_COINS_FETCH_FAIL",
  START_GAINERS_LOSERS_FETCH: "START_GAINERS_LOSERS_FETCH",
  GAINERS_LOSERS_FETCH_SUCCESS: "GAINERS_LOSERS_FETCH_SUCCESS",
  GAINERS_LOSERS_FETCH_FAIL: "GAINERS_LOSERS_FETCH_FAIL",
  NEWS_SUMMARY_FETCH: "NEWS_SUMMARY_FETCH",
  NEWS_SUMMARY_SUCCESS: "NEWS_SUMMARY_SUCCESS",
  NEWS_SUMMARY_FAIL: "NEWS_SUMMARY_FAIL",
  START_GLOBAL_SUMMARY_FETCH: "START_GLOBAL_SUMMARY_FETCH",
  GLOBAL_SUMMARY_FETCH_SUCCESS: "GLOBAL_SUMMARY_FETCH_SUCCESS",
  GLOBAL_SUMMARY_FETCH_FAIL: "GLOBAL_SUMMARY_FETCH_FAIL",
  UPDATE_TOP_COINS: "UPDATE_TOP_COINS",
  UPDATE_GAINERS_LOSERS: "UPDATE_GAINERS_LOSERS"
};

export default SUMMARY_ACTION_TYPES;
