const NOTIFICATION_ACTION_TYPES = {
  SUCCESS_NOTIFICATION: "SUCCESS_NOTIFICATION",
  ERROR_NOTIFICATION: "ERROR_NOTIFICATION",
  WARNING_NOTIFICATION: "WARNING_NOTIFICATION",
  INFO_NOTIFICATION: "INFO_NOTIFICATION",
  CLEAR_NOTIFICATION: "CLEAR_NOTIFICATION"
};

export default NOTIFICATION_ACTION_TYPES;
