const SCREEN_NAMES = {
  CHANGE_PASSWORD: "ChangePassword",
  CHANGE_EMAIL_OR_NAME: "ChangeEmailOrName",
  SELECT_TRANSACTION_COIN: "SelectTransactionCoin",
  ADD_EDIT_TRANSACTION: "AddEditTransaction",
  HOLDING_OVERVIEW: "HoldingOverview",
  LOGIN: "Login",
  SIGN_UP: "SignUp",
  BOTTOM_TABS_HOME: "BottomTabsHome",
  PRICE_ALERT: "PriceAlert",
  COMPARE_CURRENCY: "CompareCurrency",
  CONVERT_CURRENCY: "ConvertCurrency",
  SELECT_CURRENCY: "SelectCurrency",
  SELECT_HOME_SCREEN: "SelectHomeScreen",
  TERMS_AND_PRIVACY: "TermsAndPrivacy",
  ASSET_DETAIL: "AssetDetail",
  ASSET_DETAIL_OVERVIEW: "AssetDetailOverview",
  ASSET_DETAIL_MARKETS: "AssetDetailMarkets",
  ASSET_DETAIL_ABOUT: "AssetDetailAbout",
  ASSET_DETAIL_NEWS: "AssetDetailNews",
  ASSET_DETAIL_EVENTS: "AssetDetailEvents",
  DISCOVER_EVENT_FILTERS: "DiscoverEventFilters",
  ASSET_DETAIL_EVENT_FILTERS: "AssetDetailEventFilters",
  EVENT_DETAILS: "EventDetails",
  SEARCH_CRYPTO: "SearchCrypto",
  MARKET_OVERVIEW: "MarketOverview",
  DISCOVER: "Discover",
  PORTFOLIO_HOME: "PortfolioHome",
  SETTINGS: "Settings",
  HOME: "Home",
  PORTFOLIO_DRAWER: "PortfolioDrawer",
  PORTFOLIO_UNAUTHENTICATED: "PortfolioUnauthenticated",
  PORTFOLIO: "Portfolio",
  NEWS: "News",
  EVENTS: "Events"
};

export default SCREEN_NAMES;
