const MARKET_ACTION_TYPES = {
  UPDATE_FILTERS: "UPDATE_FILTERS",
  INITIAL_MARKETS_FETCH: "START_INITIAL_MARKET_FETCH",
  INITIAL_MARKETS_FAIL: "INITIAL_MARKETS_FAIL",
  INITIAL_MARKETS_SUCCESS: "INITIAL_MARKETS_SUCCESS",
  FETCH_MORE_MARKETS: "FETCH_MORE_MARKETS",
  FETCH_MORE_MARKETS_FAIL: "FETCH_MORE_MARKETS_FAIL",
  FETCH_MORE_MARKETS_SUCCESS: "FETCH_MORE_MARKETS_SUCCESS",
  NO_MORE_MARKETS: "NO_MORE_MARKETS"
};

export default MARKET_ACTION_TYPES;
