const MARKET_ACTION_TYPES = {
  UPDATE_FILTERS: "UPDATE_FILTERS",
  FETCH_MARKETS: "START_INITIAL_MARKET_FETCH",
  FETCH_MARKETS_FAIL: "FETCH_MARKETS_FAIL",
  FETCH_MARKETS_SUCCESS: "FETCH_MARKETS_SUCCESS",
  FETCH_MORE_MARKETS: "FETCH_MORE_MARKETS",
  FETCH_MORE_MARKETS_FAIL: "FETCH_MORE_MARKETS_FAIL",
  FETCH_MORE_MARKETS_SUCCESS: "FETCH_MORE_MARKETS_SUCCESS",
  NO_MORE_MARKETS: "NO_MORE_MARKETS",
  FETCH_TRENDING_SEARCHES: "FETCH_TRENDING_SEARCHES",
  FETCH_TRENDING_SEARCHES_FAIL: "FETCH_TRENDING_SEARCHES_FAIL",
  FETCH_TRENDING_SEARCHES_SUCCESS: "FETCH_TRENDING_SEARCHES_SUCCESS",
  FETCH_RECENT_SEARCHES: "FETCH_RECENT_SEARCHES",
  FETCH_RECENT_SEARCHES_FAIL: "FETCH_RECENT_SEARCHES_FAIL",
  FETCH_RECENT_SEARCHES_SUCCESS: "FETCH_RECENT_SEARCHES_SUCCESS",
  FETCH_SEARCH_RESULTS: "FETCH_SEARCH_RESULTS",
  FETCH_SEARCH_RESULTS_FAIL: "FETCH_SEARCH_RESULTS_FAIL",
  FETCH_SEARCH_RESULTS_SUCCESS: "FETCH_SEARCH_RESULTS_SUCCESS",
  UPDATE_MARKETS: "UPDATE_MARKETS"
};

export default MARKET_ACTION_TYPES;
