export default {
  ICON_SIZE: 18,
  ICON_COLOR: "white",
  CHANGE_PASSWORD_BACKGROUND_COLOR: "#1a87ff",
  CHANGE_EMAIL_BACKGROUND_COLOR: "#4ecf3b",
  LOG_OUT_BACKGROUND_COLOR: "#eb1c1b",
  DARK_MODE_BACKGROUND_COLOR: "#44484b",
  RECEIVE_NOTIFICATIONS_BACKGROUND_COLOR: "#f85a27",
  CURRENCY_BACKGROUND_COLOR: "#4ecf3b",
  HOME_SCREEN_BACKGROUND_COLOR: "#1a87ff",
  PRIVACY_MODE_BACKGROUND_COLOR: "#8c32fb",
  BIOMETRIC_BACKGROUND_COLOR: "#f85a27",
  TERMS_AND_PRIVACY_BACKGROUND_COLOR: "#44484b",
  SHARE_BACKGROUND_COLOR: "#8c32fb",
  VERSION_BACKGROUND_COLOR: "#1a87ff"
};
