const USER_ACTION_TYPES = {
  EMAIL_LOGIN: "EMAIL_LOGIN",
  AUTO_LOGIN: "AUTO_LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOG_OUT: "LOG_OUT",
  LOG_OUT_FAIL: "LOG_OUT_FAIL",
  LOG_OUT_SUCCESS: "LOG_OUT_SUCCESS",
  REGISTER: "REGISTER",
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS"
};

export default USER_ACTION_TYPES;
