const NEWS_ACTION_TYPES = {
  START_NEWS_FETCH: "START_NEWS_FETCH",
  NEWS_FETCH_SUCCESS: "NEWS_FETCH_SUCCESS",
  NEWS_FETCH_FAIL: "NEWS_FETCH_FAIL",
  START_EVENTS_FETCH: "START_EVENTS_FETCH",
  EVENTS_FETCH_SUCCESS: "EVENTS_FETCH_SUCCESS",
  EVENTS_FETCH_FAIL: "EVENTS_FETCH_FAIL",
  UPDATE_EVENT_FILTERS: "UPDATE_EVENT_FILTERS"
};

export default NEWS_ACTION_TYPES;
