const NEWS_ACTION_TYPES = {
  INITIAL_NEWS_FETCH: "INITIAL_NEWS_FETCH",
  INITIAL_NEWS_SUCCESS: "INITIAL_NEWS_SUCCESS",
  INITIAL_NEWS_FAIL: "INITIAL_NEWS_FAIL",
  FETCH_MORE_NEWS: "FETCH_MORE_NEWS",
  FETCH_MORE_NEWS_SUCCESS: "FETCH_MORE_NEWS_SUCCESS",
  FETCH_MORE_NEWS_FAIL: "FETCH_MORE_NEWS_FAIL",
  START_EVENTS_FETCH: "START_EVENTS_FETCH",
  EVENTS_FETCH_SUCCESS: "EVENTS_FETCH_SUCCESS",
  EVENTS_FETCH_FAIL: "EVENTS_FETCH_FAIL",
  UPDATE_EVENT_FILTERS: "UPDATE_EVENT_FILTERS",
  NO_MORE_NEWS: "NO_MORE_NEWS"
};

export default NEWS_ACTION_TYPES;
