const NEWS_ACTION_TYPES = {
  START_INITIAL_NEWS_FETCH: "START_INITIAL_NEWS_FETCH",
  INITIAL_NEWS_FETCH_SUCCESS: "INITIAL_NEWS_FETCH_SUCCESS",
  INITIAL_NEWS_FETCH_FAIL: "INITIAL_NEWS_FETCH_FAIL",
  FETCH_MORE_NEWS: "FETCH_MORE_NEWS",
  FETCH_MORE_NEWS_SUCCESS: "FETCH_MORE_NEWS_SUCCESS",
  FETCH_MORE_NEWS_FAIL: "FETCH_MORE_NEWS_FAIL",
  START_EVENTS_FETCH: "START_EVENTS_FETCH",
  EVENTS_FETCH_SUCCESS: "EVENTS_FETCH_SUCCESS",
  EVENTS_FETCH_FAIL: "EVENTS_FETCH_FAIL",
  UPDATE_EVENT_FILTERS: "UPDATE_EVENT_FILTERS"
};

export default NEWS_ACTION_TYPES;
