const DISCOVER_ACTION_TYPES = {
  INITIAL_NEWS_FETCH: "INITIAL_NEWS_FETCH",
  INITIAL_NEWS_SUCCESS: "INITIAL_NEWS_SUCCESS",
  INITIAL_NEWS_FAIL: "INITIAL_NEWS_FAIL",
  FETCH_MORE_NEWS: "FETCH_MORE_NEWS",
  FETCH_MORE_NEWS_SUCCESS: "FETCH_MORE_NEWS_SUCCESS",
  FETCH_MORE_NEWS_FAIL: "FETCH_MORE_NEWS_FAIL",
  INITIAL_EVENTS_FETCH: "INITIAL_EVENTS_FETCH",
  INITIAL_EVENTS_SUCCESS: "INITIAL_EVENTS_SUCCESS",
  INITIAL_EVENTS_FAIL: "INITIAL_EVENTS_FAIL",
  FETCH_MORE_EVENTS: "FETCH_MORE_EVENTS",
  FETCH_MORE_EVENTS_SUCCESS: "FETCH_MORE_EVENTS_SUCCESS",
  FETCH_MORE_EVENTS_FAIL: "FETCH_MORE_EVENTS_FAIL",
  UPDATE_EVENT_FILTERS: "UPDATE_EVENT_FILTERS",
  NO_MORE_NEWS: "NO_MORE_NEWS",
  NO_MORE_EVENTS: "NO_MORE_EVENTS"
};

export default DISCOVER_ACTION_TYPES;
