const DISCOVER_ACTION_TYPES = {
  FETCH_NEWS: "FETCH_NEWS",
  FETCH_NEWS_SUCCESS: "FETCH_NEWS_SUCCESS",
  FETCH_NEWS_FAIL: "FETCH_NEWS_FAIL",
  FETCH_MORE_NEWS: "FETCH_MORE_NEWS",
  FETCH_MORE_NEWS_SUCCESS: "FETCH_MORE_NEWS_SUCCESS",
  FETCH_MORE_NEWS_FAIL: "FETCH_MORE_NEWS_FAIL",
  FETCH_EVENTS: "FETCH_EVENTS",
  FETCH_EVENTS_SUCCESS: "FETCH_EVENTS_SUCCESS",
  FETCH_EVENTS_FAIL: "FETCH_EVENTS_FAIL",
  FETCH_MORE_EVENTS: "FETCH_MORE_EVENTS",
  FETCH_MORE_EVENTS_SUCCESS: "FETCH_MORE_EVENTS_SUCCESS",
  FETCH_MORE_EVENTS_FAIL: "FETCH_MORE_EVENTS_FAIL",
  UPDATE_EVENT_FILTERS: "UPDATE_EVENT_FILTERS",
  NO_MORE_NEWS: "NO_MORE_NEWS",
  NO_MORE_EVENTS: "NO_MORE_EVENTS"
};

export default DISCOVER_ACTION_TYPES;
