const PREFERENCES_ACTION_TYPES = {
  TOGGLE_THEME: "TOGGLE_THEME",
  TOGGLE_NOTIFICATIONS: "TOGGLE_NOTIFICATIONS",
  CHANGE_CURRENCY: "CHANGE_CURRENCY",
  CHANGE_HOME_SCREEN: "CHANGE_HOME_SCREEN",
  TOGGLE_BIOMETRIC_AUTH: "TOGGLE_BIOMETRIC_AUTH",
  TOGGLE_PRIVACY_MODE: "TOGGLE_PRIVACY_MODE"
};

export default PREFERENCES_ACTION_TYPES;
